# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafedra',
            fields=[
                ('cafedra_id', models.AutoField(primary_key=True, serialize=False)),
                ('cafedra_name', models.CharField(max_length=50)),
                ('cafedra_shifr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_date', models.DateField()),
                ('contract_sum', models.CharField(max_length=15)),
                ('payer_kind', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=10)),
                ('group_create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_sum', models.CharField(max_length=15)),
                ('document_no', models.CharField(max_length=10)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('Patronymic', models.CharField(max_length=30, null=True)),
                ('sex', models.SmallIntegerField()),
                ('birth_day', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scontract_kind',
            fields=[
                ('contract_kind_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_kind_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sdiploma',
            fields=[
                ('diploma_id', models.AutoField(primary_key=True, serialize=False)),
                ('diploma_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sfinance',
            fields=[
                ('finance_id', models.AutoField(primary_key=True, serialize=False)),
                ('finance_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Smark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=50)),
                ('speciality_shifr', models.CharField(max_length=10)),
                ('caferda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_no', models.CharField(max_length=15)),
                ('note', models.TextField(max_length=255, null=True)),
                ('diploma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sdiploma')),
                ('finance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sfinance')),
                ('person_student_fk', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person')),
                ('specialize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Student_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('putting_date', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Groups')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Smark')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='speciality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Speciality'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_kind_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Scontract_kind'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Student'),
        ),
    ]
