# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smark',
            name='old_type_mark',
            field=models.SmallIntegerField(default=1),
        ),
    ]
