# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_smark_old_type_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smark',
            name='old_type_mark',
            field=models.FloatField(default=1, max_length=3),
        ),
    ]
